[Fix] Unified links of readthedocs in docs
open-mmlab/mmsegmentation pull request #1119
Opened 2021-12-09 06:51 UTC by MengzhangLI

Related PR: https://github.com/open-mmlab/mim/pull/89

Note: 
(1) MMSegmentation has adopted `pytorch_sphinx_theme` from https://github.com/open-mmlab/mmsegmentation/pull/879.

(2) Currently, some repos do not have Chinese readthe docs, they are `mmhuman3d`, `mmflow` and `mmgeneration`, thus just keep their url. We may change it in the future.

2021-12-09 07:38 UTC, Junjun2016 approved these changes

2021-12-09 07:41 UTC, Junjun2016 requested changes
The menu is not correct.
Please check the pre-builded readthedoc.

2021-12-09 10:01 UTC, gaotongxiao commented
These changes are no longer required and can be simplified as in https://github.com/open-mmlab/mmocr/pull/655

2021-12-10 08:49 UTC, Junjun2016 approved these changes

2021-12-10 08:49 UTC, merged