[Docs] Add MultiImageMixDataset tutorial
open-mmlab/mmsegmentation pull request #1194
Opened 2022-01-11 04:18 UTC by RockeyCoss

Thanks for your contribution and we appreciate it a lot. The following instructions would make your pull request more healthy and more easily get feedback. If you do not understand some items, don't worry, just make the pull request and seek help from maintainers.

## Motivation

Add MultiImageMixDataset tutorial

## Modification

Add MultiImageMixDataset tutorial

2022-01-11 04:23 UTC, Junjun2016 reviewed
Add related PRs to PR messages, e.g. MultiImageMixDataset and Mosaic.

2022-01-12 04:10 UTC, Junjun2016 approved these changes

2022-01-12 15:12 UTC, lkm2835 commented on docs/en/tutorials/customize_datasets.md
> +    dict(type='Mosaic'),
`dict(type='Mosaic')`
-> `dict(type='RandomMosaic', prob=1)`

I think it's better to modify it.

2022-01-12 15:12 UTC, lkm2835 commented on docs/zh_cn/tutorials/customize_datasets.md
> +    dict(type='Mosaic'),
`dict(type='Mosaic')`
-> `dict(type='RandomMosaic', prob=1)`

2022-01-12 15:15 UTC, lkm2835 requested changes

2022-01-12 15:15 UTC, lkm2835 commented on docs/en/tutorials/customize_datasets.md
> +    dict(type='Mosaic'),
`dict(type='Mosaic')`
-> `dict(type='RandomMosaic', prob=1)`

I think it's better to modify it.

2022-01-12 15:15 UTC, lkm2835 commented on docs/zh_cn/tutorials/customize_datasets.md
> +    dict(type='Mosaic'),
`dict(type='Mosaic')`
-> `dict(type='RandomMosaic', prob=1)`

2022-01-12 16:08 UTC, MengzhangLI commented
It is ok except `dict(type='Mosaic')` may be modified to `dict(type='RandomMosaic', prob=1)`.

2022-01-12 16:09 UTC, MengzhangLI approved these changes

2022-01-21 13:48 UTC, MengzhangLI approved these changes

2022-01-22 10:11 UTC, MeowZheng commented on docs/en/tutorials/customize_datasets.md
> +```python
![image](https://user-images.githubusercontent.com/76149310/150634286-e99782d8-e7bb-4b53-8284-451cf27d901a.png)

MD031/blanks-around-fences: Fenced code blocks should be surrounded by blank lines

2022-01-22 10:11 UTC, MeowZheng commented on docs/zh_cn/tutorials/customize_datasets.md
> +```python
MD031/blanks-around-fences: Fenced code blocks should be surrounded by blank lines

2022-01-24 07:48 UTC, MeowZheng approved these changes

2022-01-24 07:48 UTC, merged