[Docs] Add Chinese dataflow markdown
open-mmlab/mmsegmentation pull request #2652
Opened 2023-02-27 10:42 UTC by AI-Tianlong

## Modification
Add Chinese dataflow markdown

2023-02-28 00:47 UTC, csatsurnh commented
Please add extra space between Chinese and English characters/numbers, e.g.
我们将介绍[Runner](https://mmengine.readthedocs.io/zh_CN/latest/tutorials/runner.html)管理的内部模块之间的数据流和数据格式约定。 --> 我们将介绍 [Runner](https://mmengine.readthedocs.io/zh_CN/latest/tutorials/runner.html) 管理的内部模块之间的数据流和数据格式约定。
共计20000次迭代 --> 共计 20000 次迭代

2023-02-28 00:58 UTC, csatsurnh commented on docs/zh_cn/advanced_guides/data_flow.md
> +虚线边框、灰色填充形状代表不同的数据格式，而实心框表示模块/方法。由于 MMEngine 的极大灵活性和可扩展性，一些重要的基类可以被继承，并且它们的方法可以被覆写。 上图所示数据流仅适用于当用户没有自定义 `Runner`中的`TrainLoop`、`ValLoop` 和 `TestLoop`，并且没有在其自定义模型中覆写`train_step`、`val_step`和`test_step`方
由于 MMEngine 的极大灵活性和可扩展性 --> 由于 MMEngine 极大的灵活性和可扩展性

2023-02-28 00:59 UTC, csatsurnh commented on docs/zh_cn/advanced_guides/data_flow.md
> +在上图中，红色线表示[train_step](https://github.com/open-mmlab/mmsegmentation/blob/dev-1.x/docs/en/advanced_guides/models.md#train_step)***（[中文链接待更新](https://github.com/open-mmlab/mmsegmentation/blob/dev-1.x/d
数据加载器(dataloader)从存储中 --> 数据加载器（dataloader）从存储中

2023-02-28 01:09 UTC, AI-Tianlong commented on docs/zh_cn/advanced_guides/data_flow.md
> +在上图中，红色线表示[train_step](https://github.com/open-mmlab/mmsegmentation/blob/dev-1.x/docs/en/advanced_guides/models.md#train_step)***（[中文链接待更新](https://github.com/open-mmlab/mmsegmentation/blob/dev-1.x/d
Fixed

2023-02-28 01:10 UTC, AI-Tianlong commented on docs/zh_cn/advanced_guides/data_flow.md
> +虚线边框、灰色填充形状代表不同的数据格式，而实心框表示模块/方法。由于 MMEngine 的极大灵活性和可扩展性，一些重要的基类可以被继承，并且它们的方法可以被覆写。 上图所示数据流仅适用于当用户没有自定义 `Runner`中的`TrainLoop`、`ValLoop` 和 `TestLoop`，并且没有在其自定义模型中覆写`train_step`、`val_step`和`test_step`方
Fixed

2023-02-28 01:10 UTC, AI-Tianlong commented
> Please add extra space between Chinese and English characters/numbers, e.g. 我们将介绍[Runner](https://mmengine.readthedocs.io/zh_CN/latest/tutorials/runner.html)管理的内部模块之间的数据流和数据格式约定。 --> 我们将介绍 [Runner](https://mmengine.readthedocs.io/zh_CN/latest/tutorials/runner.html) 管理的内部模块之间的数据流和数据格式约定。 共计20000次迭代 --> 共计 20000 次迭代

2023-02-28 01:12 UTC, AI-Tianlong commented on docs/zh_cn/advanced_guides/data_flow.md
> +在上图中，红色线表示[train_step](https://github.com/open-mmlab/mmsegmentation/blob/dev-1.x/docs/en/advanced_guides/models.md#train_step)***（[中文链接待更新](https://github.com/open-mmlab/mmsegmentation/blob/dev-1.x/d
Sorry, I accidentally closed PR😥

2023-02-28 01:35 UTC, csatsurnh commented on docs/zh_cn/advanced_guides/data_flow.md
> +在上图中，红色线表示 [train_step](https://github.com/open-mmlab/mmsegmentation/blob/dev-1.x/docs/en/advanced_guides/models.md#train_step) ***（[中文链接待更新](https://github.com/open-mmlab/mmsegmentation/blob/dev-1.x
“数据加载器 (dataloader) 从存储中” 这个是需要用全角括号，不是半角加空格

2023-02-28 01:43 UTC, AI-Tianlong commented on docs/zh_cn/advanced_guides/data_flow.md
> +在上图中，红色线表示 [train_step](https://github.com/open-mmlab/mmsegmentation/blob/dev-1.x/docs/en/advanced_guides/models.md#train_step) ***（[中文链接待更新](https://github.com/open-mmlab/mmsegmentation/blob/dev-1.x
😀

2023-02-28 04:24 UTC, csatsurnh reviewed
另外，正文（非全英）冒号均需使用全角

2023-02-28 04:24 UTC, csatsurnh commented on docs/zh_cn/advanced_guides/data_flow.md
> +在MMSegmentation中, `decode_head` 的 [loss_by_feat](https://github.com/open-mmlab/mmsegmentation/blob/dev-1.x/mmseg/models/decode_heads/decode_head.py#L291) 方法是用于计算损失的统一接口。
add space

2023-02-28 04:24 UTC, csatsurnh commented on docs/zh_cn/advanced_guides/data_flow.md
> +**注意:**  `train_step` 将损失传递进OptimWrapper以更新模型中的权重, 更多信息请参阅 [train_step](https://github.com/open-mmlab/mmsegmentation/blob/dev-1.x/docs/en/advanced_guides/models.md#train_step)。 ***（[中文链接待更新](https://
add space

2023-02-28 04:24 UTC, csatsurnh commented on docs/zh_cn/advanced_guides/data_flow.md
> +- batch_data_samples (List\[:obj:`SegDataSample`\]): seg 数据样本，通常包括如 `metainfo` 和  `gt_sem_seg`等信息
seg 数据样本 --> 分割数据样本

2023-02-28 04:24 UTC, csatsurnh commented on docs/zh_cn/advanced_guides/data_flow.md
> +返回:
返回值

2023-02-28 04:24 UTC, csatsurnh commented on docs/zh_cn/advanced_guides/data_flow.md
> +- dict\[str, Tensor\]: 损失组件的字典
一个损失组件的字典

2023-02-28 04:24 UTC, csatsurnh commented on docs/zh_cn/advanced_guides/data_flow.md
> +虽然在[上面的图](https://github.com/open-mmlab/mmsegmentation/edit/dev-1.x/docs/zh_cn/advanced_guides/data_flow.md#%E6%95%B0%E6%8D%AE%E6%B5%81%E7%A8%8B%E6%A6%82%E8%BF%B0)中分开绘制了数据预处理器和模型，但数据预处理器是模型的一部分，因此可以在
https://github.com/open-mmlab/mmsegmentation/edit/dev-1.x/docs/zh_cn/advanced_guides/data_flow.md#%E6%95%B0%E6%8D%AE%E6%B5%81%E7%A8%8B%E6%A6%82%E8%BF%B0
-->
#数据流程概述

2023-03-01 03:57 UTC, csatsurnh requested changes
Can I have the access to your repo so that I can modify some little format issue

2023-03-02 00:39 UTC, AI-Tianlong commented
> Can I have the access to your repo so that I can modify some little format issue

Of course. What should I do to give you access?

2023-03-02 01:21 UTC, csatsurnh commented
> > Can I have the access to your repo so that I can modify some little format issue
> 
> Of course. What should I do to give you access?



> > Can I have the access to your repo so that I can modify some little format issue
> 
> Of course. What should I do to give you access?

Sorry, it's done

2023-03-02 01:28 UTC, csatsurnh approved these changes

2023-03-02 01:39 UTC, MeowZheng commented on docs/zh_cn/advanced_guides/data_flow.md
> +- batch_data_samples (List\[:obj:`SegDataSample`\])：分割数据样本，通常包括如 `metainfo` 和  `gt_sem_seg` 等信息
```suggestion
- batch_data_samples (List\[SegDataSample\])：分割数据样本，通常包括如 `metainfo` 和  `gt_sem_seg` 等信息
```

2023-03-02 01:40 UTC, MeowZheng approved these changes

2023-03-02 01:56 UTC, merged