[Enhancement] Modify interface of MMSeginferencer and add docs
open-mmlab/mmsegmentation pull request #2658
Opened 2023-02-28 15:13 UTC by MeowZheng

Thanks for your contribution and we appreciate it a lot. The following instructions would make your pull request more healthy and more easily get feedback. If you do not understand some items, don't worry, just make the pull request and seek help from maintainers.

## Motivation

Make MMSeginferencer easier to be used

## Modification

1. Add `_load_weights_to_model` to MMSeginferencer, it is for get `dataset_meta` from ckpt
2. Modify and remove some parameters of `__call__`, `visualization` and `postprocess`
3. Add function of save seg mask, remove dump pkl.
4. Refine docstring of MMSeginferencer and SegLocalVisualizer
5. Add the user documentation of MMSeginferencer

## BC-breaking (Optional)

yes, remove some parameters, we need to discuss whether keep them with deprecated waring or just remove them as the  MMSeginferencer just merged in mmseg a few days. 

## Use cases (Optional)

If this PR introduces a new feature, it is better to list some use cases here, and update the documentation.

## Checklist

1. Pre-commit or other linting tools are used to fix the potential lint issues.
6. The modification is covered by complete unit tests. If not, please add more unit test to ensure the correctness.
7. If the modification has potential influence on downstream projects, this PR should be tested with downstream projects, like MMDet or MMDet3D.
8. The documentation has been modified accordingly, like docstring or example tutorials.

2023-03-02 10:07 UTC, csatsurnh requested changes
For classes and palette docstring in local_visualizer, whether delete default to cityscapes in classes or add default to cityscapes in palette, not sure which is better.

2023-03-03 04:55 UTC, xiexinch commented on mmseg/visualization/local_visualizer.py
> +            dataset_name (str, optional): `Dataset name or alias <https://github.com/open-mmlab/mmsegmentation/blob/a35e1c4232a03503a2d549206ca703d3850d5244/mmseg/utils/class_names.py#L302-L317>`_
```suggestion
            dataset_name (str, optional): `Dataset name or alias <https://github.com/open-mmlab/mmsegmentation/blob/dev-1.x/mmseg/utils/class_names.py#L302-L317>`_
```

2023-03-03 05:39 UTC, xiexinch approved these changes

2023-03-03 06:30 UTC, csatsurnh approved these changes

2023-03-03 06:37 UTC, merged