[Feature] Add segformer decode head and related train config
open-mmlab/mmsegmentation pull request #599
Opened 2021-06-11 07:48 UTC by sennnnn

- [ ]  Add head SegFormerHead;

- [ ]  Add some config for segformer;

2021-06-11 09:20 UTC, AncientRemember commented
are the imgsize parameter of MixVisionTransformer is necessary？ segformer drop the position encoding and make the model inductive when test resolution is diff with train

2021-06-21 05:26 UTC, Junjun2016 commented
> are the imgsize parameter of MixVisionTransformer is necessary？ segformer drop the position encoding and make the model inductive when test resolution is diff with train

In my opinion, the image size is not necessary, we will refactor it.

2021-06-21 05:43 UTC, Junjun2016 commented on mmseg/models/decode_heads/segformer_head.py
> +
Remove some redundant blank lines.

2021-06-21 05:48 UTC, Junjun2016 commented on mmseg/models/decode_heads/segformer_head.py
> +
Another suggestion is whether the kernel size of these two ConvModule can be passed in by Args.

2021-07-27 06:04 UTC, sennnnn commented
## About the influence of AlignedResize for performance

| Model | Crop Size | Resize Mode | mIoU |
| :-- | :-- | :-- | :-- |
| Segformer_MIT-B0 | 512x512 | Normal | 37.41 | 
| Segformer_MIT-B1 | 512x512 | Normal | 41.05 | 
| Segformer_MIT-B2 | 512x512 | Normal | 45.68 | 
| Segformer_MIT-B0 | 512x512 | Aligned | 38.1 | 
| Segformer_MIT-B1 | 512x512 | Aligned | 41.75 | 
| Segformer_MIT-B2 | 512x512 | Aligned | - |

2021-07-30 01:06 UTC, xvjiarui commented on mmseg/models/decode_heads/segformer_head.py
> +    """The all mlp Head of segformer.
Add reference. 

Follow the style of other heads.

2021-07-30 01:06 UTC, xvjiarui commented on tools/deploy_test.py
> +            seg_pred = resize(
Why change this?

2021-07-30 01:06 UTC, xvjiarui commented on mmseg/models/decode_heads/segformer_head.py
> +class SegformerHead(BaseDecodeHead):
Unittest is missing.

2021-07-30 01:07 UTC, xvjiarui commented on mmseg/models/decode_heads/segformer_head.py
> +
```suggestion
```

2021-07-30 01:08 UTC, xvjiarui commented on mmseg/models/decode_heads/segformer_head.py
> +        for x, conv in zip(inputs, self.convs):
`zip` is not safe since it will stop at the short one. 

Use int to index `x` and `convs`

2021-07-30 06:29 UTC, Junjun2016 commented on tools/deploy_test.py
> +            seg_pred = resize(
#731

2021-07-30 07:08 UTC, xvjiarui commented on configs/segformer/segformer_mit-b0_512x512_160k_ade20k.py
> +    pretrained='pretrain/mit_b0.pth', decode_head=dict(num_classes=150))
update pretrain path

2021-07-31 16:41 UTC, xvjiarui commented on mmseg/datasets/pipelines/transforms.py
> +    def _align(self, img, interpolation=None):
Use https://github.com/open-mmlab/mmcv/blob/571e3e5fc75c23b45cbd9b00011af094357c5f1d/mmcv/image/geometric.py#L98 instead.

2021-07-31 16:41 UTC, xvjiarui commented on mmseg/datasets/pipelines/transforms.py
> +            results[key] = gt_seg
Merge in to call instead.

2021-07-31 16:45 UTC, xvjiarui commented on configs/segformer/readme.md
> +We replace `AlignedResize` to `Resize + ResizeToMultiple`. If you want to test by
```suggestion
We replace `AlignedResize` in original implementatiuon to `Resize + ResizeToMultiple`. If you want to test by
```

2021-07-31 16:46 UTC, xvjiarui commented on configs/segformer/readme.md
> +            dict(type='ResizeToMultiple', size_divisor=32),
```suggestion
            # resize image to multiple of 32, improve SegFormer by xx mIoU. 
            dict(type='ResizeToMultiple', size_divisor=32),
```

2021-08-10 06:07 UTC, xvjiarui commented on configs/segformer/readme.md
> +            dict(type='ResizeToMultiple', size_divisor=32),
We may replace xx with a concrete number.

2021-08-10 17:29 UTC, xvjiarui commented on configs/segformer/readme.md
> +Because the MixVisionTransformer is not supported by mmcls, we just can get backbone weights from official repo. We provide convert script to convert official weights in `tools/model_converters/mit_c
```suggestion
We convert the backbone weights from the official repo (https://github.com/NVlabs/SegFormer) with `tools/model_converters/mit_convert.py`.
```
Also add cmd example.

2021-08-10 17:30 UTC, xvjiarui commented on tools/model_converters/mit_convert.py
> +    ckpt = torch.load(src_path)
```suggestion
    ckpt = torch.load(src_path, map_location='cpu')
```

2021-08-10 17:30 UTC, xvjiarui commented on tools/model_converters/mit_convert.py
> +        ckpt = ckpt
The official weight should only contain 1 case.

2021-08-11 02:11 UTC, xvjiarui approved these changes

2021-08-12 06:00 UTC, Junjun2016 commented on tests/test_data/test_transform.py
> +def test_align():
```suggestion
def test_resize_to_multiple():
```

2021-08-12 06:20 UTC, Junjun2016 requested changes

2021-08-12 06:20 UTC, Junjun2016 commented on configs/segformer/segformer_mit-b1_512x512_160k_ade20k.py
> +    '../_base_/models/segformer_mit-b0.py', '../_base_/datasets/ade20k.py',
Inherit from `configs/segformer/segformer_mit-b0_512x512_160k_ade20k.py`.

2021-08-12 06:20 UTC, Junjun2016 commented on configs/segformer/segformer_mit-b1_512x512_160k_ade20k.py
> +data = dict(samples_per_gpu=2)
Can be inherit from `configs/segformer/segformer_mit-b0_512x512_160k_ade20k.py`?

2021-08-12 06:20 UTC, Junjun2016 commented on configs/segformer/segformer_mit-b1_512x512_160k_ade20k.py
> +    decode_head=dict(in_channels=[64, 128, 320, 512], num_classes=150))
```suggestion
    decode_head=dict(in_channels=[64, 128, 320, 512]))
```

2021-08-12 06:20 UTC, Junjun2016 commented on configs/segformer/segformer_mit-b2_512x512_160k_ade20k.py
> +    '../_base_/models/segformer_mit-b0.py', '../_base_/datasets/ade20k.py',
Inherit from `configs/segformer/segformer_mit-b0_512x512_160k_ade20k.py`.

2021-08-12 06:20 UTC, Junjun2016 commented on configs/segformer/segformer_mit-b2_512x512_160k_ade20k.py
> +    '../_base_/models/segformer_mit-b0.py', '../_base_/datasets/ade20k.py',
The same as above.

2021-08-12 06:20 UTC, Junjun2016 commented on configs/segformer/segformer_mit-b0_512x512_160k_ade20k.py
> +data = dict(samples_per_gpu=2)
workers_per_gpu=2

2021-08-12 06:20 UTC, Junjun2016 commented on configs/segformer/segformer_mit-b3_512x512_160k_ade20k.py
> +    '../_base_/models/segformer_mit-b0.py', '../_base_/datasets/ade20k.py',
The same as aforementioned.

2021-08-12 06:20 UTC, Junjun2016 commented on configs/segformer/segformer_mit-b4_512x512_160k_ade20k.py
> +    '../_base_/models/segformer_mit-b0.py', '../_base_/datasets/ade20k.py',
The same as aforementioned.

2021-08-12 06:20 UTC, Junjun2016 commented on configs/segformer/segformer_mit-b5_512x512_160k_ade20k.py
> +    '../_base_/models/segformer_mit-b0.py', '../_base_/datasets/ade20k.py',
The same as aforementioned.

2021-08-12 06:20 UTC, Junjun2016 commented on configs/segformer/segformer_mit-b5_640x640_160k_ade20k.py
> +    '../_base_/models/segformer_mit-b0.py', '../_base_/default_runtime.py',
Inherit from `configs/segformer/segformer_mit-b5_512x512_160k_ade20k.py`

2021-08-12 06:20 UTC, Junjun2016 commented on configs/segformer/segformer_mit-b5_640x640_160k_ade20k.py
> +    '../_base_/models/segformer_mit-b0.py', '../_base_/default_runtime.py',
After inherited, only need overwrite `pipeline` in `data`.

2021-08-12 06:20 UTC, Junjun2016 commented on mmseg/models/decode_heads/segformer_head.py
> +    `Segformer <https://arxiv.org/abs/2105.15203>`
> This head is the implementation of `DNLNet
>     <https://arxiv.org/abs/2006.06668>`_.

Missing `_`, please refer to other heads.

2021-08-12 06:20 UTC, Junjun2016 commented on tools/model_converters/mit_convert.py
> +    parser = argparse.ArgumentParser()
```suggestion
    parser = argparse.ArgumentParser(description='')
```

It is better to add some descriptions or docstring about this script.

2021-08-13 05:29 UTC, Junjun2016 approved these changes

2021-08-13 05:31 UTC, merged