add isa module
open-mmlab/mmsegmentation pull request #70
Opened 2020-08-16 04:00 UTC by LayneH

2020-08-16 04:00 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/open-mmlab/mmsegmentation?pullRequest=70) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/open-mmlab/mmsegmentation?pullRequest=70) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/open-mmlab/mmsegmentation?pullRequest=70) it.</sub>

2020-08-19 07:56 UTC, xvjiarui commented on mmseg/models/decode_heads/__init__.py
> +    'ISAHead',
The comma could be removed.

2020-08-19 08:24 UTC, xvjiarui commented on mmseg/models/decode_heads/isa_head.py
> +        isa_channels (int): The channels of ISA Module.
Missing arguments.

2020-08-19 08:25 UTC, xvjiarui commented on mmseg/models/decode_heads/isa_head.py
> +        Q_h, Q_w = math.ceil(h / P_h), math.ceil(w / P_w)
We may use more readable variable names.

2020-08-19 08:26 UTC, xvjiarui commented on mmseg/models/decode_heads/isa_head.py
> +        feat = self.global_relation(feat)
Add comments about shape.

2020-08-19 08:26 UTC, xvjiarui commented on mmseg/models/decode_heads/isa_head.py
> +        feat = self.local_relation(feat)
Add comments about shape.

2020-08-19 08:26 UTC, xvjiarui commented on mmseg/models/decode_heads/isa_head.py
> +                                                      P_w * Q_w)
Add comments about shape.

2021-07-04 18:55 UTC, Junjun2016 commented
Hi @LayneH 
Could you please update this PR if your time is available?

2021-08-24 08:03 UTC, LayneH commented
Hi, @xvjiarui  @Junjun2016,

This PR has been updated according to the comments.

2021-08-24 08:10 UTC, Junjun2016 commented
Hi @LayneH 
Thanks for your contribution.
Could you please resolve the conflict?
And we will review it again.

2021-08-24 08:11 UTC, Junjun2016 commented on configs/_base_/models/isanet_r50-d8.py
> +test_cfg = dict(mode='whole')
`train_cfg` and `test_cfg` have been moved to model.

2021-08-24 08:14 UTC, Junjun2016 commented on configs/isanet/README.md
> +```
Add tag `<!-- [ALGORITHM] --> `to README, please refer to the README of OCRNet.

2021-08-24 08:20 UTC, Junjun2016 commented on mmseg/models/decode_heads/isa_head.py
> +        channels (int): Output channels of key/query transform.
Missing docstring for `conv_cfg`, `norm_cfg`,  and `act_cfg`.

2021-08-24 08:22 UTC, Junjun2016 commented on mmseg/models/decode_heads/isa_head.py
> +    <https://arxiv.org/abs/1907.12273>`.
```suggestion
    <https://arxiv.org/abs/1907.12273>`_.
```

2021-08-24 08:22 UTC, Junjun2016 commented on mmseg/models/decode_heads/isa_head.py
> +    <https://arxiv.org/abs/1907.12273>`.
The citation style is not correct.
Please refer to https://github.com/open-mmlab/mmsegmentation/blob/master/mmseg/models/backbones/mobilenet_v3.py#L19.

2021-08-24 08:26 UTC, Junjun2016 reviewed
Please add unittests for `mmseg/models/decode_heads/isa_head.py`.
We will benchmark it recently.

2021-08-24 08:29 UTC, Junjun2016 commented
`configs/_base_/models/.isanet_r50-d8.py.swp` should be removed.

2021-08-24 08:35 UTC, Junjun2016 commented
> Please add unittests for `mmseg/models/decode_heads/isa_head.py`.
> We will benchmark it recently.

Refer to https://github.com/open-mmlab/mmsegmentation/blob/master/tests/test_models/test_heads/test_ocr_head.py.

2021-08-24 10:12 UTC, Junjun2016 commented on mmseg/models/decode_heads/isa_head.py
> +        conv_cfg (dict|None): Config of conv layers.
```suggestion
        conv_cfg (dict | None): Config of conv layers.
```

2021-08-24 10:12 UTC, Junjun2016 commented on mmseg/models/decode_heads/isa_head.py
> +        norm_cfg (dict|None): Config of norm layers.
```suggestion
        norm_cfg (dict | None): Config of norm layers.
```

2021-08-24 10:12 UTC, Junjun2016 commented on mmseg/models/decode_heads/isa_head.py
> +        act_cfg (dict|None): Config of activation layers.
```suggestion
        act_cfg (dict | None): Config of activation layers.
```

2021-08-24 13:52 UTC, Junjun2016 commented
Hi @LayneH 
The unittests are failed.
Please also refer to https://github.com/open-mmlab/mmsegmentation/blob/master/tests/test_models/test_heads/test_dnl_head.py.

2021-08-24 16:17 UTC, LayneH commented
Hi @Junjun2016,
The issue has been fixed.

2021-08-24 16:55 UTC, Junjun2016 commented
> Hi @Junjun2016,
> The issue has been fixed.

Ok, we will add benchmarks for ISA recently.

2021-09-01 07:05 UTC, Junjun2016 commented on configs/isanet/isanet_r50-d8_512x512_160k_ade20k.py
> +test_cfg = dict(mode='whole')
`train_cfg` and `test_cfg` have been moved to `model`, and` test_cfg = dict(mode='whole')` has already defined in `configs/_base_/models/isanet_r50-d8.py`, so this line is redundant.

2021-09-01 07:10 UTC, Junjun2016 requested changes

2021-09-01 07:10 UTC, Junjun2016 commented on configs/isanet/isanet_r50-d8_512x512_80k_ade20k.py
> +test_cfg = dict(mode='whole')
`train_cfg` and `test_cfg` have been moved to `model`, and` test_cfg = dict(mode='whole')` has already defined in `configs/_base_/models/isanet_r50-d8.py`, so this line is redundant.

2021-09-01 07:10 UTC, Junjun2016 commented on configs/isanet/isanet_r50-d8_769x769_40k_cityscapes.py
> +test_cfg = dict(mode='slide', crop_size=(769, 769), stride=(513, 513))
Same.

2021-09-01 07:10 UTC, Junjun2016 commented on configs/isanet/isanet_r50-d8_769x769_80k_cityscapes.py
> +test_cfg = dict(mode='slide', crop_size=(769, 769), stride=(513, 513))
Same.

2021-09-01 07:10 UTC, Junjun2016 commented on configs/isanet/isanet_r50-d8_769x769_40k_cityscapes.py
> +test_cfg = dict(mode='slide', crop_size=(769, 769), stride=(513, 513))
Move `test_cfg` to `model`.

2021-09-01 07:10 UTC, Junjun2016 commented on configs/isanet/isanet_r50-d8_769x769_80k_cityscapes.py
> +test_cfg = dict(mode='slide', crop_size=(769, 769), stride=(513, 513))
Move `test_cfg` to `model`.

2021-09-01 07:10 UTC, Junjun2016 commented on configs/isanet/isanet_r50-d8_769x769_40k_cityscapes.py
> +test_cfg = dict(mode='slide', crop_size=(769, 769), stride=(513, 513))
If `train_cfg` or `test_cfg` is different from default, we should overwrite it.

2021-09-01 07:12 UTC, Junjun2016 commented
Please also fix the conflict.
We are running benchmark.
We will update the results when we finish it.

2021-09-01 07:55 UTC, LayneH commented
Hi, the conflicts have been fixed.

2021-09-07 04:50 UTC, xiexinch commented
Hi @Junjun2016 
Results updated.

2021-09-07 10:29 UTC, LayneH commented
@xiexinch @Junjun2016 
Thank you for the benchmarking, the results seem to be consistent with those in our paper.

2021-09-07 10:53 UTC, Junjun2016 requested changes
Please add supported methods in README (English and Chinese).

2021-09-07 13:44 UTC, Junjun2016 approved these changes

2021-09-09 04:13 UTC, xvjiarui approved these changes

2021-09-09 04:13 UTC, merged

2023-04-07 02:54 UTC, OpenMMLab-Assistant003 commented
Hi @LayneH！First of all, we want to express our gratitude for your significant PR in the MMSegmentation project. Your contribution is highly appreciated, and we are grateful for your efforts in helping improve this open-source project during your personal time. We believe that many developers will benefit from your PR.

We would also like to invite you to join our Special Interest Group (SIG) private channel on Discord, where you can share your experiences, ideas, and build connections with like-minded peers. To join the SIG channel, simply message moderator— OpenMMLab on Discord or briefly share your open-source contributions in the #introductions channel and we will assist you. Look forward to seeing you there! Join us ：https://discord.gg/UjgXkPWNqA

If you have WeChat account，welcome to join our community on WeChat. You can add our assistant ：openmmlabwx. Please add "mmsig + Github ID" as a remark when adding friends：）
Thank you again for your contribution❤ @LayneH