[Fix] Convert SyncBN to BN when training on DP
open-mmlab/mmsegmentation pull request #772
Opened 2021-08-10 12:18 UTC by sennnnn

### Incompatible between DP and SyncBN

run this command without setting `--launcher`:

```base
python tools/train.py [config_path]
```

The python environment will report about process group: 

`RuntimeError: Default process group has not been initialized, please make sure to call init_process_group.`

This error is caused by `SyncBN`. When `SyncBN.training` is True, `SyncBN` need to init `process_group`. However, `process_group` is only valid when `DDP`.

The situation that SyncBN is valid:
* `process_group` is not None or `torch.distributed.group.WORLD` is not `None`;
* `SyncBN.training` is False or `SyncBN.eval()`;

Based on those mentioned above, we convert SyncBN to BN when training on DP.

2021-08-10 17:48 UTC, xvjiarui commented
May move to `models/utils`

2021-08-31 08:52 UTC, Junjun2016 commented on tools/train.py
> +    # SyncBN is not support for single gpu
```suggestion
    # SyncBN is not support for DP
```

2021-08-31 08:55 UTC, Junjun2016 commented on tools/train.py
> +            'SyncBN tp BN. Please to use dist_train.py which has official '
```suggestion
            'SyncBN to BN. Please use dist_train.sh which can '
```

2021-08-31 08:55 UTC, Junjun2016 commented on tools/train.py
> +            'support to avoid this problem.')
```suggestion
            'this problem.')
```

2021-08-31 09:08 UTC, Junjun2016 requested changes
Please fix the conflict.

2021-08-31 16:12 UTC, Junjun2016 approved these changes

2021-08-31 17:03 UTC, xvjiarui commented
https://github.com/open-mmlab/mmcv/pull/1253

2021-09-02 06:10 UTC, Junjun2016 commented
We can import from mmcv after it merged.

2021-09-08 05:36 UTC, Junjun2016 commented
Can import `revert_sync_batchnorm` from https://github.com/open-mmlab/mmcv/pull/1253

2021-09-11 17:37 UTC, Junjun2016 commented on docker/serve/Dockerfile
> +ARG MMCV="1.3.13"
Should also update mmcv version [here](https://github.com/open-mmlab/mmsegmentation/blob/master/docker/Dockerfile#L4).

2021-09-11 18:15 UTC, Junjun2016 commented on tools/train.py
> +            'SyncBN only support DDP. In order to compat with DP, we convert '
```suggestion
            'SyncBN is only supported with DDP. To be compatible with DP, we convert '
```

2021-09-11 18:16 UTC, Junjun2016 reviewed
Please fix the conflict.

2021-09-13 06:17 UTC, Junjun2016 approved these changes
LGTM

2021-09-15 03:14 UTC, xvjiarui commented
Please upgrade mmcv requirement.

2021-09-15 03:18 UTC, Junjun2016 reviewed
https://github.com/open-mmlab/mmsegmentation/blob/master/docs/get_started.md#installation

Update mmcv dependence of master branch.

2021-09-15 14:08 UTC, Junjun2016 approved these changes
LGTM

2021-09-15 16:39 UTC, merged